<a href="https://colab.research.google.com/github/zunish629-bit/python-task/blob/main/Numpy_task_1_5_(all_method).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Name: Zunaira Sheikh
#Roll no: AI-868278


In [ ]:
#Task 1
import numpy as np

var=np.array([10,20,30,40,50])
print(var)
print("----------------")
print(var+4)
print(np.average(var))
print(np.max(var))
print(np.min(var))
print("------------------")




[10 20 30 40 50]
----------------
[14 24 34 44 54]
30.0
50
10
------------------


In [ ]:
#Task 2
num=np.array([45, 80, 30, 90, 55, 20])
print(num)

print("''''''''''''''")

print((num)[num>=50])

[45 80 30 90 55 20]
''''''''''''''
[80 90 55]


In [ ]:
#Task 3

num=np.array([1, 2, 3, 4, 5, 6])
print(num.shape)

(6,)


In [ ]:
#Task 4
num=np.random.randint(40,100,10)
print("Random num:", num)
print("********************************")
print("Average :",np.mean(num))
print("Maximum :",np.max(num))
print("Minimum :",np.min(num))

Random num: [68 40 55 66 57 98 52 91 67 79]
********************************
Average : 67.3
Maximum : 98
Minimum : 40


In [ ]:
#Task 5
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])
passing_marks = 50

passed_marks = marks[marks >= passing_marks]
failed_marks = marks[marks < passing_marks]

num_passed = len(passed_marks)
num_failed = len(failed_marks)
print("Passed marks:", passed_marks)
print("Failed marks:", failed_marks)
print("Number of passed students:", num_passed)
print("Number of failed students:", num_failed)


Passed marks: [67 89 90 70 58]
Failed marks: [35 45 22]
Number of passed students: 5
Number of failed students: 3
